package fi.agisol.checkout.api.persistence;

import org.joda.time.DateTime;

/**
 * Interface for persistent objects which are created, stored and retrieved withTransactionRepository
 * 
 * @author www.agisol.fi
 */
public interface TransactionEntity {
	
	/**
	 * Get start time of the transaction
	 * @return startTime of the transaction
	 */
	DateTime getStartTime();

	/**
	 * Set start time of the transaction
	 * @param startTime of the transaction
	 */
	void setStartTime(DateTime startTime);

	/**
	 * Get end time of the transaction
	 * @return endTime of the transaction
	 */
	DateTime getEndTime();

	/**
	 * Set end time of the transaction
	 * @param endTime of the transaction
	 */
	void setEndTime(DateTime endTime);

	/***
	 * Get stamp of the payment
	 * @return stamp is internally generated id of the payment
	 */
	String getStamp();

	/***
	 * Set stamp of the payment
	 * @param stamp is internally generated id of the payment
	 */
	void setStamp(String stamp);

	/**
	 * Get Checkout generated payment identifier
	 * @return paymentId generated by Checkout
	 */
	String getPaymentId();

	/**
	 * Set Checkout generated payment identifier
	 * @param paymentId generated by Checkout
	 */
	void setPaymentId(String paymentId);

	/** 
	 * Get custom information about payment/order
	 * @return message information about the payment/order
	 */
	String getMessage();

	/** 
	 * Set custom information about payment/order
	 * @param message - information about the payment/order (Optional) 
	 */
	void setMessage(String message);

	/**
	 * Get payment amount of the payment in euro-cents
	 * @return paymentAmount 
	 */
	Integer getAmount();

	/**
	 * Set payment amount of the payment in euro-cents (Mandatory)
	 * @param paymentAmount 
	 */
	void setAmount(Integer amount);

	/***
	 * Get status of the payment 
	 * More info from:
	 *  - http://www.checkout.fi/materiaalit/tekninen-materiaali/
	 *  - page 5/7 -> http://www.checkout.fi/wp-content/uploads/2015/04/CTD-Tekninenrajapintakuvaus-210415-1146-170.pdf
	 *
	 * @return status
	 */
	Integer getStatus();

	/***
	 * Set status of the payment
	 *  More info from:
	 *  - http://www.checkout.fi/materiaalit/tekninen-materiaali/
	 *  - page 5/7 -> http://www.checkout.fi/wp-content/uploads/2015/04/CTD-Tekninenrajapintakuvaus-210415-1146-170.pdf
	 *
	 * @parameter status
	 */
	void setStatus(Integer status);

	/***
	 * Get internally set extra information about transaction
	 * (used Eg. to put error texts in case of payment failure)
	 * @return information
	 */
	String getInformation();

	/***
	 * Set extra information about transaction
	 * (used Eg. to put error texts in case of payment failure)
	 * @param information
	 */
	void setInformation(String information);

	/**
	 * Get check time of the transaction
	 * @return checkTime of the transaction
	 */
	DateTime getCheckTime();

	/**
	 * Set check time of the transaction
	 * @param checkTime of the transaction
	 */
	void setCheckTime(DateTime checkTime);

	/***
	 * Get reference of the payment
	 * @return reference
	 */
	String getReference();

	/***
	 * Set reference of the payment
	 * @parameter reference
	 */
	void setReference(String reference);

}