package fi.agisol.checkout.api.persistence;

/**
 * Interface to create and persist the payment transactions (between startPayment, updatePayment and endPayment)
 * 
 * @author www.agisol.fi
 */
public interface TransactionRepository {

	/**
	 * Creates new TransactionEntity (NOTE: to implementation - don't persist the object yet!)
	 * 
	 * 	@param stamp is unique identifier generated by internally "checkout-java"
	 * 	@param paymentId is unique identifier generated by "checkout.fi"
	 * 	@param reference number of the payment
	 * 	@param amount of the payment in euro-cents
	 * 	@param message is custom information about payment/order
	 * @return TransactionEntity
	 */
	TransactionEntity create(String stamp, String paymentId, String reference, Integer amount, String message);
	
	/**
	 * Saves new transaction or updates existing one and returns the saved transaction
	 * @param transactionEntity new or updated transaction which contains information about the payment 
	 * @return saved TransactionEntity
	 */
	TransactionEntity save(TransactionEntity transactionEntity);

	/**
	 * Finds TransactionEntity stamp
	 * @param stamp is unique identifier generated internally by "checkout-java"
	 * @return saved TransactionEntity
	 */
	TransactionEntity findByStamp(String stamp);
	
}
